version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: queue-user
      RABBITMQ_DEFAULT_PASS: ToPSecreT

  quotefeeder:
    image: huferry/quote-feeder:1
    depends_on:
      - rabbitmq
    environment:
      QUEUE_HOST: rabbitmq
      QUEUE_USER: queue-user
      QUEUE_PASSWORD: ToPSecreT

  quoteview:
    image: huferry/quote-view:8
    depends_on:
      - rabbitmq
    ports:
      - "80:80"
    environment:
      QUEUE_HOST: rabbitmq
      QUEUE_USER: queue-user
      QUEUE_PASSWORD: ToPSecreT