apiVersion: apps/v1
kind: Deployment
metadata:
  name: quotefeeder-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotefeeder
  template:
    metadata:
      labels:
        app: quotefeeder
    spec:
      containers:
      - name: quotefeeder-container
        image: huferry/quote-feeder:2
        env:
        - name: QUEUE_HOST
          value: quotes-amqp-service
        - name: QUEUE_USER
          valueFrom:
            secretKeyRef:
              name: quotes-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quotes-secrets
              key: RABBITMQ_DEFAULT_PASS