apiVersion: apps/v1
kind: Deployment
metadata:
  name: quoteview-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quoteview
  template:
    metadata:
      labels:
        app: quoteview
    spec:
      containers:
      - name: quoteview-container
        image: huferry/quote-view:5
        ports:
        - name: quote-view-port
          containerPort: 80
        env:
        - name: QUEUE_HOST
          value: quotes-amqp-service
        - name: QUEUE_USER
          valueFrom:
            secretKeyRef:
              name: quotes-secrets
              key: RABBITMQ_DEFAULT_USER
        - name: QUEUE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: quotes-secrets
              key: RABBITMQ_DEFAULT_PASS
           